"use client";
import {useEffect,useMemo,useState} from "react";import {Button} from "../../components/ui/button";import {Badge} from "../../components/ui/badge";
const api=process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/,"")??"http://localhost:4000/api";
export default function Page(){
 const[leads,setLeads]=useState<any[]>([]),[campaigns,setCampaigns]=useState<any[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[showCreate,setShowCreate]=useState(false),[selected,setSelected]=useState<any>(null),[status,setStatus]=useState("ALL"),[minFit,setMinFit]=useState(0),[search,setSearch]=useState(""),[running,setRunning]=useState("");
 const[form,setForm]=useState({name:"",product:"Hyaw Workforce",query:"cafes restaurants retail shops hotels clinics salons workshops logistics construction manufacturing and other businesses with employees",location:"Addis Ababa Ethiopia",industry:"",targetNotes:"Start with Hyaw Workforce. Target small and medium businesses that manage employees, shifts or attendance: cafes, restaurants, retail, hotels, clinics, salons, workshops, logistics, construction and manufacturing. Prioritize businesses with no dedicated website or weak digital presence. Exclude software/HR vendors, directories and articles as actual leads."});
 async function load(){try{const[a,c]=await Promise.all([fetch(api+"/ai-leads",{credentials:"include"}),fetch(api+"/ai-leads/campaigns",{credentials:"include"})]);const ab=await a.json(),cb=await c.json();if(!a.ok)throw new Error(ab.message||"Could not load AI leads");setLeads(ab.data||[]);setCampaigns(cb.data||[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load")}}
 useEffect(()=>{void load()},[]);
 async function create(e:any){e.preventDefault();const r=await fetch(api+"/ai-leads/campaigns",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const b=await r.json();if(!r.ok){setError(b.message||"Could not create campaign");return}setForm({...form,name:""});setShowCreate(false);await load()}
 async function run(id:string){setError("");setMessage("");setRunning(id);try{const r=await fetch(api+"/ai-leads/campaigns/"+id+"/run",{method:"POST",credentials:"include"});const b=await r.json();if(!r.ok)throw new Error(b.message||"Discovery failed");setMessage(`Discovery complete: ${b.data.processed||0} prospects, ${b.data.excluded||0} excluded, ${b.data.duplicates||0} duplicates, ${b.data.aiPending||0} awaiting AI review.`);await load()}catch(e){setError(e instanceof Error?e.message:"Discovery failed")}finally{setRunning("")}}
 async function decision(id:string,type:"accept"|"reject"){const reason=type==="reject"?(window.prompt("Why are you rejecting this lead?","Not relevant")||"Rejected by salesperson"):undefined;const r=await fetch(api+"/ai-leads/"+id+"/"+type,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason})});const b=await r.json();if(!r.ok){setError(b.message||"Action failed");return}setSelected(null);await load()}
 const filtered=useMemo(()=>leads.filter(l=>(status==="ALL"||l.status===status)&&Number(l.fitScore)>=minFit&&(!search||String(l.company).toLowerCase().includes(search.toLowerCase())||String(l.industry||"").toLowerCase().includes(search.toLowerCase()))),[leads,status,minFit,search]);
 return <div className="placeholderPage"><header><div><p className="eyebrow">AI sales intelligence</p><h1>AI Lead Finder</h1><p>Discover prospects, exclude competing vendors, qualify against your ICP and automatically create CRM leads for salesperson review.</p></div></header>
 {error?<p className="dataError">{error}</p>:null}{message?<p>{message}</p>:null}
 <div className="ui-card"><div className="ui-card-content"><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:16}}><div><h2>Discovery campaigns</h2><p style={{margin:0}}>Create targeting rules and fetch fresh prospects.</p></div><Button onClick={()=>setShowCreate(true)}>+ Create campaign</Button></div>{campaigns.map(c=><div key={c.id} style={{display:"flex",justifyContent:"space-between",gap:12,padding:"12px 0",borderBottom:"1px solid var(--border)"}}><span><strong>{c.name}</strong><br/><small>{c.product} · {c.query}</small></span><Button disabled={running===c.id} onClick={()=>void run(c.id)}>{running===c.id?"Searching...":"Search now"}</Button></div>)}</div></div>
 <div className="ui-card"><div className="ui-card-content"><div style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"end",marginBottom:16}}><label>Search<input className="ui-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Company or industry"/></label><label>Status<select className="ui-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All</option><option value="QUALIFIED">Qualified</option><option value="REVIEWED">Review</option><option value="CONVERTED">Accepted</option><option value="REJECTED">Rejected</option><option value="EXCLUDED">Excluded</option></select></label><label>Minimum fit<input className="ui-input" type="number" min="0" max="100" value={minFit} onChange={e=>setMinFit(Number(e.target.value))}/></label></div>
 <div style={{overflowX:"auto"}}><table className="ui-table" style={{width:"100%"}}><thead><tr><th>Company</th><th>Industry</th><th>Location</th><th>Fit</th><th>Qualification</th><th>Campaign</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(l=><tr key={l.id} onClick={()=>setSelected(l)} style={{cursor:"pointer"}}><td><strong>{l.company}</strong><br/><small>{l.businessType||"Unknown type"}</small></td><td>{l.industry||"—"}</td><td>{l.location||"—"}</td><td><Badge>{l.fitScore}% · {l.priority}</Badge></td><td>{l.isCompetitor?"Competitor/vendor":l.qualificationReason||"Needs review"}</td><td>{l.campaign?.name||"—"}</td><td><Badge>{l.status}</Badge></td><td onClick={e=>e.stopPropagation()}>{l.convertedLeadId&&l.status==="QUALIFIED"?<span style={{display:"flex",gap:6}}><Button onClick={()=>void decision(l.id,"accept")}>Accept</Button><Button variant="outline" onClick={()=>void decision(l.id,"reject")}>Reject</Button></span>:<Button variant="ghost" onClick={()=>setSelected(l)}>View</Button>}</td></tr>)}</tbody></table>{!filtered.length?<p>No leads match these filters.</p>:null}</div></div></div>
 {showCreate?<div style={{position:"fixed",inset:0,zIndex:80,background:"rgba(15,23,42,.48)",display:"grid",placeItems:"center",padding:20}} onMouseDown={()=>setShowCreate(false)}><section className="ui-card" style={{width:"min(680px,100%)",maxHeight:"90vh",overflowY:"auto"}} onMouseDown={e=>e.stopPropagation()}><div className="ui-card-content"><div style={{display:"flex",justifyContent:"space-between"}}><div><p className="eyebrow">AI lead discovery</p><h2>Create discovery campaign</h2></div><Button variant="ghost" onClick={()=>setShowCreate(false)}>×</Button></div><form onSubmit={create}><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:16}}>{Object.entries(form).map(([k,v])=><label key={k} style={k==="query"||k==="targetNotes"?{gridColumn:"1 / -1"}:undefined}>{k.replace(/([A-Z])/g," $1")}<input className="ui-input" required={["name","product","query"].includes(k)} value={v} onChange={e=>setForm(x=>({...x,[k]:e.target.value}))}/></label>)}</div><div style={{display:"flex",justifyContent:"flex-end",gap:10,marginTop:24}}><Button type="button" variant="outline" onClick={()=>setShowCreate(false)}>Cancel</Button><Button type="submit">Create campaign</Button></div></form></div></section></div>:null}
 {selected?<div style={{position:"fixed",inset:0,zIndex:85,background:"rgba(15,23,42,.35)",display:"flex",justifyContent:"flex-end"}} onMouseDown={()=>setSelected(null)}><aside className="ui-card" style={{width:"min(560px,100%)",height:"100%",borderRadius:0,overflowY:"auto"}} onMouseDown={e=>e.stopPropagation()}><div className="ui-card-content"><div style={{display:"flex",justifyContent:"space-between"}}><div><p className="eyebrow">{selected.status}</p><h2>{selected.company}</h2></div><Button variant="ghost" onClick={()=>setSelected(null)}>×</Button></div><p><strong>Qualification:</strong> {selected.qualificationReason||"Needs human review."}</p><p><strong>Confidence:</strong> {selected.confidence||0}% · <strong>Fit:</strong> {selected.fitScore}%</p><p>{selected.description||"No source description."}</p><h3>Likely problems</h3><p>{Array.isArray(selected.likelyProblems)?selected.likelyProblems.join(" · "):"—"}</p><h3>Calling strategy</h3><p>{selected.strategy||"Only generated for qualified prospects."}</p>{selected.openingLine?<blockquote>{selected.openingLine}</blockquote>:null}<p><strong>First call goal:</strong> {selected.firstCallGoal||"—"}</p><p><a href={selected.sourceUrl} target="_blank" rel="noreferrer">Open source evidence</a></p>{selected.convertedLeadId&&selected.status==="QUALIFIED"?<div style={{display:"flex",gap:8}}><Button onClick={()=>void decision(selected.id,"accept")}>Accept lead</Button><Button variant="outline" onClick={()=>void decision(selected.id,"reject")}>Reject</Button></div>:null}</div></aside></div>:null}
 </div>
}
