import {getPlatformValue} from "./platform-ai-settings";
type LeadForExpert={company:string;description?:string|null;industry?:string|null;location?:string|null;website?:string|null};
type Campaign={product:string;targetNotes?:string|null};
type AiProvider="GROQ"|"OPENAI"|"GEMINI"|"ANTHROPIC";
export type CallExpertResult={fitScore:number;priority:"LOW"|"MEDIUM"|"HIGH";isPotentialCustomer:boolean;isCompetitor:boolean;businessType:string;confidence:number;qualificationReason:string;likelyProblems:string[];strategy:string;openingLine:string;firstCallGoal:string;objections:{objection:string;response:string}[];nextAction:string};
const fallback=(lead:LeadForExpert,c:Campaign):CallExpertResult=>({fitScore:50,priority:"MEDIUM",isPotentialCustomer:false,isCompetitor:false,businessType:"UNKNOWN",confidence:0,qualificationReason:"AI qualification unavailable; requires human review.",likelyProblems:["Needs discovery during the first call"],strategy:`Learn how ${lead.company} currently handles the problem that ${c.product} solves before pitching.`,openingLine:`Hi, I'm calling from Hyaw Tech. I wanted to understand how ${lead.company} currently handles this area of the business.`,firstCallGoal:"Understand the current process, pain level and decision maker.",objections:[],nextAction:"CALL"});
const defaults:Record<AiProvider,string>={GROQ:"openai/gpt-oss-120b",OPENAI:"gpt-5.6-luna",GEMINI:"gemini-3.8-flash",ANTHROPIC:"claude-sonnet-4-6"};
async function complete(provider:AiProvider,key:string,model:string,prompt:string){
 if(provider==="GROQ"||provider==="OPENAI"){const base=provider==="GROQ"?"https://api.groq.com/openai/v1":"https://api.openai.com/v1";const r=await fetch(base+"/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,temperature:.2,response_format:{type:"json_object"},messages:[{role:"user",content:prompt}]})});if(!r.ok)throw new Error(`${provider} strategy failed: ${r.status}`);const b:any=await r.json();return b.choices?.[0]?.message?.content}
 if(provider==="GEMINI"){const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:"application/json",temperature:.2}})});if(!r.ok)throw new Error(`GEMINI strategy failed: ${r.status}`);const b:any=await r.json();return b.candidates?.[0]?.content?.parts?.[0]?.text}
 const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"x-api-key":key,"anthropic-version":"2023-06-01","Content-Type":"application/json"},body:JSON.stringify({model,max_tokens:1800,temperature:.2,messages:[{role:"user",content:prompt}]})});if(!r.ok)throw new Error(`ANTHROPIC strategy failed: ${r.status}`);const b:any=await r.json();return b.content?.find((x:any)=>x.type==="text")?.text
}
export async function buildCallingStrategy(lead:LeadForExpert,campaign:Campaign):Promise<CallExpertResult>{
 const provider=((await getPlatformValue("aiProvider"))||"GROQ").toUpperCase() as AiProvider;
 const key=(await getPlatformValue("aiApiKey"))||(provider==="GROQ"?await getPlatformValue("groqApiKey"):"");if(!key)return fallback(lead,campaign);
 const model=(await getPlatformValue("aiModel"))||(provider==="GROQ"?await getPlatformValue("groqModel"):"")||defaults[provider]||defaults.GROQ;
 const prompt=`You are the strict qualification gate for a B2B sales lead engine. Hyaw Tech is selling: ${campaign.product}. Ideal-customer notes: ${campaign.targetNotes||"none"}. Candidate evidence: ${JSON.stringify(lead)}. First decide whether this organization is actually a potential CUSTOMER for the product. Companies primarily selling HR software, payroll software, attendance/time systems, workforce-management software, recruitment/HR outsourcing, ERP HR modules, or substantially competing services must be classified as competitors/vendors, NOT prospects. Do not force a fit. Use only the supplied evidence for factual claims. Any possible pain not explicitly supported by evidence must be phrased as a hypothesis. Return ONLY valid JSON: {isPotentialCustomer:boolean,isCompetitor:boolean,businessType:string,confidence:0-100,qualificationReason:string,fitScore:0-100,priority:"LOW"|"MEDIUM"|"HIGH",likelyProblems:string[],strategy:string,openingLine:string,firstCallGoal:string,objections:[{objection:string,response:string}],nextAction:string}. For non-prospects/competitors, keep strategy/openingLine/firstCallGoal empty and nextAction="EXCLUDE".`;
 const raw=await complete(provider,key,model,prompt);if(!raw)return fallback(lead,campaign);const x=JSON.parse(raw);return {fitScore:Math.max(0,Math.min(100,Number(x.fitScore)||0)),isPotentialCustomer:x.isPotentialCustomer===true,isCompetitor:x.isCompetitor===true,businessType:String(x.businessType||"UNKNOWN"),confidence:Math.max(0,Math.min(100,Number(x.confidence)||0)),qualificationReason:String(x.qualificationReason||""),priority:["LOW","MEDIUM","HIGH"].includes(x.priority)?x.priority:"MEDIUM",likelyProblems:Array.isArray(x.likelyProblems)?x.likelyProblems.slice(0,6):[],strategy:String(x.strategy||""),openingLine:String(x.openingLine||""),firstCallGoal:String(x.firstCallGoal||""),objections:Array.isArray(x.objections)?x.objections.slice(0,6):[],nextAction:String(x.nextAction||"CALL")};
}
