import {getPlatformValue} from "./platform-ai-settings";
type LeadForExpert={company:string;description?:string|null;industry?:string|null;location?:string|null;website?:string|null};
type Campaign={product:string;targetNotes?:string|null};
export type CallExpertResult={fitScore:number;priority:"LOW"|"MEDIUM"|"HIGH";likelyProblems:string[];strategy:string;openingLine:string;firstCallGoal:string;objections:{objection:string;response:string}[];nextAction:string};
const fallback=(lead:LeadForExpert,c:Campaign):CallExpertResult=>({fitScore:50,priority:"MEDIUM",likelyProblems:["Needs discovery during the first call"],strategy:`Learn how ${lead.company} currently handles the problem that ${c.product} solves before pitching.`,openingLine:`Hi, I'm calling from Hyaw Tech. I wanted to understand how ${lead.company} currently handles this area of the business.`,firstCallGoal:"Understand the current process, pain level and decision maker.",objections:[],nextAction:"CALL"});
export async function buildCallingStrategy(lead:LeadForExpert,campaign:Campaign):Promise<CallExpertResult>{
 const key=await getPlatformValue("groqApiKey");if(!key)return fallback(lead,campaign);
 const prompt=`You are a B2B lead qualification and cold-calling expert for Hyaw Tech. Product: ${campaign.product}. Target notes: ${campaign.targetNotes||"none"}. Prospect: ${JSON.stringify(lead)}. Return ONLY JSON with fitScore 0-100, priority LOW|MEDIUM|HIGH, likelyProblems string[], strategy, openingLine, firstCallGoal, objections [{objection,response}], nextAction. Do not invent facts; phrase uncertain pains as hypotheses.`;
 const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:(await getPlatformValue("groqModel"))||"llama-3.3-70b-versatile",temperature:.2,response_format:{type:"json_object"},messages:[{role:"user",content:prompt}]})});
 if(!r.ok)throw new Error(`Groq strategy failed: ${r.status}`);const body:any=await r.json();const raw=body.choices?.[0]?.message?.content;if(!raw)return fallback(lead,campaign);const x=JSON.parse(raw);return {fitScore:Math.max(0,Math.min(100,Number(x.fitScore)||0)),priority:["LOW","MEDIUM","HIGH"].includes(x.priority)?x.priority:"MEDIUM",likelyProblems:Array.isArray(x.likelyProblems)?x.likelyProblems.slice(0,6):[],strategy:String(x.strategy||""),openingLine:String(x.openingLine||""),firstCallGoal:String(x.firstCallGoal||""),objections:Array.isArray(x.objections)?x.objections.slice(0,6):[],nextAction:String(x.nextAction||"CALL")};
}
