import type {SearchCandidate} from "./lead-formatter";import {getPlatformValue} from "./platform-ai-settings";
type Provider="SERPER"|"BRAVE"|"TAVILY"|"EXA";
const clean=(items:any[],source:string):SearchCandidate[]=>items.map((x:any)=>({title:String(x.title||x.name||""),link:String(x.link||x.url||""),snippet:x.snippet||x.description||x.text?String(x.snippet||x.description||x.text):undefined,source})).filter((x:SearchCandidate)=>x.title&&x.link);
export async function searchPublicLeads(query:string):Promise<SearchCandidate[]>{const provider=((await getPlatformValue("leadSearchProvider"))||"SERPER").toUpperCase() as Provider;const key=await getPlatformValue("leadSearchApiKey");if(!key)throw new Error(provider+" lead search API key is not configured");
if(provider==="SERPER"){const r=await fetch("https://google.serper.dev/search",{method:"POST",headers:{"X-API-KEY":key,"Content-Type":"application/json"},body:JSON.stringify({q:query,num:20})});if(!r.ok)throw new Error("Serper lead search failed: "+r.status);const b:any=await r.json();return clean(b.organic||[],"serper")}
if(provider==="BRAVE"){const r=await fetch("https://api.search.brave.com/res/v1/web/search?q="+encodeURIComponent(query)+"&count=20",{headers:{"X-Subscription-Token":key,"Accept":"application/json"}});if(!r.ok)throw new Error("Brave lead search failed: "+r.status);const b:any=await r.json();return clean(b.web?.results||[],"brave")}
if(provider==="TAVILY"){const r=await fetch("https://api.tavily.com/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({api_key:key,query,max_results:20,search_depth:"basic"})});if(!r.ok)throw new Error("Tavily lead search failed: "+r.status);const b:any=await r.json();return clean(b.results||[],"tavily")}
if(provider==="EXA"){const r=await fetch("https://api.exa.ai/search",{method:"POST",headers:{"x-api-key":key,"Content-Type":"application/json"},body:JSON.stringify({query,numResults:20})});if(!r.ok)throw new Error("Exa lead search failed: "+r.status);const b:any=await r.json();return clean(b.results||[],"exa")}
throw new Error("Unsupported lead search provider: "+provider)}
