import {Router} from "express";import {z} from "zod";import {prisma} from "../db";import {requireAuth,requirePermission} from "../auth";import {runLeadDiscovery} from "../workers/lead-fetcher";import {buildCallingStrategy} from "../services/calling-expert";
export const aiLeadsRouter=Router();aiLeadsRouter.use(requireAuth);aiLeadsRouter.use(requirePermission("settings.manage"));const tid=(r:any)=>String(r.auth!.tenantId);
aiLeadsRouter.get("/",requirePermission("lead.view"),async(req,res,next)=>{try{
 const page=Math.max(1,Number(req.query.page)||1),pageSize=Math.min(100,Math.max(1,Number(req.query.pageSize)||25)),search=String(req.query.search||"").trim();
 const status=String(req.query.status||""),campaignId=String(req.query.campaignId||""),businessType=String(req.query.businessType||""),competitor=String(req.query.competitor||"ALL"),dbState=String(req.query.dbState||"ALL"),minFit=Math.min(100,Math.max(0,Number(req.query.minFit)||0));
 const where:any={tenantId:tid(req),fitScore:{gte:minFit}};
 if(search)where.OR=[{company:{contains:search,mode:"insensitive"}},{name:{contains:search,mode:"insensitive"}},{industry:{contains:search,mode:"insensitive"}},{location:{contains:search,mode:"insensitive"}},{phone:{contains:search,mode:"insensitive"}},{sourceName:{contains:search,mode:"insensitive"}}];
 if(status&&status!=="ALL")where.status=status;if(campaignId&&campaignId!=="ALL")where.campaignId=campaignId;if(businessType&&businessType!=="ALL")where.businessType=businessType;
 if(competitor==="YES")where.isCompetitor=true;if(competitor==="NO")where.isCompetitor=false;
 if(dbState==="REGISTERED")where.convertedLeadId={not:null};if(dbState==="SEARCHED")where.convertedLeadId=null;
 const [data,total]=await Promise.all([prisma.discoveredLead.findMany({where,include:{campaign:true},orderBy:[{fitScore:"desc"},{discoveredAt:"desc"}],skip:(page-1)*pageSize,take:pageSize}),prisma.discoveredLead.count({where})]);
 const enriched=data.map(x=>({...x,databaseState:x.convertedLeadId?"REGISTERED":"SEARCHED"}));
 res.json({data:enriched,pagination:{page,pageSize,total,totalPages:Math.max(1,Math.ceil(total/pageSize))}});
}catch(e){next(e)}});
aiLeadsRouter.get("/campaigns",requirePermission("lead.view"),async(req,res,next)=>{try{res.json({data:await prisma.leadCampaign.findMany({where:{tenantId:tid(req)},orderBy:{createdAt:"desc"}})})}catch(e){next(e)}});
aiLeadsRouter.post("/campaigns",requirePermission("lead.create"),async(req,res,next)=>{try{const p=z.object({name:z.string().min(2),product:z.string().min(2),query:z.string().min(2),location:z.string().optional(),industry:z.string().optional(),targetNotes:z.string().optional()}).safeParse(req.body);if(!p.success){res.status(400).json({message:"Invalid campaign",issues:p.error.issues});return}res.status(201).json({data:await prisma.leadCampaign.create({data:{tenantId:tid(req),...p.data}})})}catch(e){next(e)}});
aiLeadsRouter.post("/campaigns/:id/run",requirePermission("lead.create"),async(req,res)=>{try{
 const c=await prisma.leadCampaign.findFirst({where:{id:String(req.params.id),tenantId:tid(req)}});
 if(!c){res.status(404).json({message:"Campaign not found"});return}
 const staleBefore=new Date(Date.now()-30*60*1000);
 if(c.runStatus==="RUNNING"&&c.runStartedAt&&c.runStartedAt>staleBefore){res.status(409).json({message:"Discovery is already running for this campaign"});return}
 const startedAt=new Date();
 await prisma.leadCampaign.update({where:{id:c.id},data:{runStatus:"RUNNING",runMessage:"Searching for prospects...",runStartedAt:startedAt}});
 void runLeadDiscovery(c.id).then(async result=>{
  await prisma.leadCampaign.update({where:{id:c.id},data:{runStatus:"COMPLETED",runMessage:`Discovery complete: ${result.processed} prospects, ${result.excluded} excluded, ${result.duplicates} duplicates, ${result.aiPending} awaiting AI review.`,lastRunAt:new Date(),lastRunResult:result as any}});
 }).catch(async error=>{
  const message=error instanceof Error?error.message:"Lead discovery failed";
  console.error("Lead discovery background run failed",c.id,error);
  await prisma.leadCampaign.update({where:{id:c.id},data:{runStatus:"FAILED",runMessage:message,lastRunAt:new Date()}}).catch(updateError=>console.error("Could not persist discovery failure",updateError));
 });
 res.status(202).json({data:{started:true,campaignId:c.id,runStatus:"RUNNING"}});
}catch(e){const message=e instanceof Error?e.message:"Could not start lead discovery";console.error("Lead discovery start failed",String(req.params.id),e);res.status(500).json({message})}});
aiLeadsRouter.post("/:id/analyze",requirePermission("lead.update"),async(req,res,next)=>{try{const lead=await prisma.discoveredLead.findFirst({where:{id:String(req.params.id),tenantId:tid(req)},include:{campaign:true}});if(!lead){res.status(404).json({message:"AI lead not found"});return}const s=await buildCallingStrategy(lead,lead.campaign);res.json({data:await prisma.discoveredLead.update({where:{id:lead.id},data:{fitScore:s.fitScore,priority:s.priority,likelyProblems:s.likelyProblems,strategy:s.strategy,openingLine:s.openingLine,firstCallGoal:s.firstCallGoal,objections:s.objections as any,nextAction:s.nextAction,status:"REVIEWED"}})})}catch(e){next(e)}});
aiLeadsRouter.post("/:id/convert",requirePermission("lead.create"),async(req,res,next)=>{try{const d=await prisma.discoveredLead.findFirst({where:{id:String(req.params.id),tenantId:tid(req)}});if(!d){res.status(404).json({message:"AI lead not found"});return}if(d.convertedLeadId){res.status(409).json({message:"Lead already converted",leadId:d.convertedLeadId});return}const parts=d.name.trim().split(/\s+/);const firstName=parts.shift()||d.company;const lastName=parts.join(" ")||"Business";const lead=await prisma.lead.create({data:{tenantId:tid(req),ownerId:typeof req.body?.ownerId==="string"?req.body.ownerId:undefined,firstName,lastName,email:d.email,phone:d.phone,company:d.company,title:d.industry,source:`AI discovery: ${d.sourceName||"web"}`,score:d.fitScore}});await prisma.discoveredLead.update({where:{id:d.id},data:{status:"CONVERTED",convertedLeadId:lead.id}});res.status(201).json({data:lead})}catch(e){next(e)}});
aiLeadsRouter.patch("/:id/reject",requirePermission("lead.update"),async(req,res,next)=>{try{const d=await prisma.discoveredLead.findFirst({where:{id:String(req.params.id),tenantId:tid(req)}});if(!d){res.status(404).json({message:"AI lead not found"});return}const reason=typeof req.body?.reason==="string"?req.body.reason.slice(0,240):"Rejected by salesperson";if(d.convertedLeadId)await prisma.lead.updateMany({where:{id:d.convertedLeadId,tenantId:tid(req)},data:{status:"LOST"}});res.json({data:await prisma.discoveredLead.update({where:{id:d.id},data:{status:"REJECTED",rejectionReason:reason}})})}catch(e){next(e)}});
aiLeadsRouter.patch("/:id/accept",requirePermission("lead.update"),async(req,res,next)=>{try{const d=await prisma.discoveredLead.findFirst({where:{id:String(req.params.id),tenantId:tid(req)}});if(!d){res.status(404).json({message:"AI lead not found"});return}if(!d.convertedLeadId){res.status(409).json({message:"CRM lead has not been created yet"});return}await prisma.lead.updateMany({where:{id:d.convertedLeadId,tenantId:tid(req)},data:{status:"CONTACTED"}});res.json({data:await prisma.discoveredLead.update({where:{id:d.id},data:{status:"CONVERTED"}})})}catch(e){next(e)}});
