"use client";
import {useEffect,useState} from "react";
import {CreateModal,type CreateField} from "../components/create-modal";
import {Badge} from "../../components/ui/badge";
import {Button} from "../../components/ui/button";
const apiUrl=process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/,"")??"http://localhost:4000/api";
const stages=["NEW","CONTACTED","QUALIFIED","PROPOSAL","WON","LOST"] as const;
const fields:CreateField[]=[
{name:"firstName",label:"First name",required:true},{name:"lastName",label:"Last name",required:true},
{name:"email",label:"Email",type:"email"},{name:"phone",label:"Phone",type:"tel"},{name:"title",label:"Job title"},
{name:"company",label:"Company"},{name:"source",label:"Source",type:"select",options:["Website","Referral","Cold call","Social media","Event","Other"]},
{name:"status",label:"Status",type:"select",options:[...stages]},{name:"score",label:"Lead score (0-100)",type:"number"},
{name:"estimatedValue",label:"Estimated value (ETB)",type:"number"},{name:"nextFollowUpAt",label:"Next follow-up",type:"date"},
{name:"ownerId",label:"Owner",type:"select",options:[]},
];
export default function Page(){const[data,setData]=useState<any[]>([]),[team,setTeam]=useState<any[]>([]),[error,setError]=useState(""),[view,setView]=useState<"kanban"|"table">("kanban");
async function load(){try{const[r,t]=await Promise.all([fetch(apiUrl+"/workspace/leads",{credentials:"include"}),fetch(apiUrl+"/workspace/team",{credentials:"include"})]);const b=await r.json();if(!r.ok)throw new Error(b.message||"Could not load leads");setData(Array.isArray(b.data)?b.data:[]);if(t.ok){const tb=await t.json();setTeam(Array.isArray(tb.data)?tb.data:[])}setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load leads")}}
useEffect(()=>{void load()},[]);
const ownerOptions=team.map((m:any)=>({value:m.user.id,label:[m.user.firstName,m.user.lastName].filter(Boolean).join(" ")}));
const modalFields=fields.map(f=>f.name==="ownerId"?{...f,options:ownerOptions}:f) as any;
async function create(values:Record<string,string>){const r=await fetch(apiUrl+"/workspace/leads",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});const b=await r.json();if(!r.ok)throw new Error(b.message||"Could not create lead");await load()}
async function move(id:string,status:string){const previous=data;setData(x=>x.map(l=>l.id===id?{...l,status}:l));const r=await fetch(apiUrl+"/workspace/leads/"+id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok){setData(previous);const b=await r.json().catch(()=>({}));setError(b.message||"Could not update lead")}}
return <div className="placeholderPage"><header><div><p className="eyebrow">Sales workspace</p><h1>Leads</h1><p>Capture, qualify and move leads through your sales process.</p></div><div className="actions"><Button variant="outline" onClick={()=>setView(view==="kanban"?"table":"kanban")}>{view==="kanban"?"Table view":"Kanban view"}</Button><CreateModal entity="lead" fields={modalFields} onCreated={create}/></div></header>{error?<p className="dataError">{error}</p>:null}{view==="kanban"?<div className="leadKanban">{stages.map(stage=><section className="kanbanColumn" key={stage} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData("leadId");if(id)void move(id,stage)}}><div className="kanbanHead"><strong>{stage.replace("_"," ")}</strong><Badge>{data.filter(x=>x.status===stage).length}</Badge></div><div className="kanbanCards">{data.filter(x=>x.status===stage).map(l=><article className="leadCard" draggable onDragStart={e=>e.dataTransfer.setData("leadId",l.id)} key={l.id}><div><strong>{l.firstName} {l.lastName}</strong><span>{l.title||l.company||"No company"}</span></div><p>{l.company||"—"}</p><div className="leadMeta"><span>ETB {Number(l.estimatedValue||0).toLocaleString()}</span><span>Score {l.score??0}</span></div><div className="leadMeta"><span>{l.source||"No source"}</span><span>{l.owner?[l.owner.firstName,l.owner.lastName].join(" "):"Unassigned"}</span></div>{l.nextFollowUpAt?<small>Follow up {new Date(l.nextFollowUpAt).toLocaleDateString()}</small>:null}<select value={l.status} onChange={e=>void move(l.id,e.target.value)}>{stages.map(s=><option value={s} key={s}>{s}</option>)}</select></article>)}</div></section>)}</div>:<div className="ui-card"><div className="ui-card-content"><table className="ui-table"><thead><tr><th>Lead</th><th>Company / title</th><th>Contact</th><th>Source</th><th>Owner</th><th>Value</th><th>Score</th><th>Status</th><th>Follow-up</th></tr></thead><tbody>{data.map(l=><tr key={l.id}><td><strong>{l.firstName} {l.lastName}</strong></td><td>{l.company||"—"}<br/><small>{l.title||""}</small></td><td>{l.email||"—"}<br/><small>{l.phone||""}</small></td><td>{l.source||"—"}</td><td>{l.owner?[l.owner.firstName,l.owner.lastName].join(" "):"Unassigned"}</td><td>ETB {Number(l.estimatedValue||0).toLocaleString()}</td><td>{l.score??0}</td><td><select value={l.status} onChange={e=>void move(l.id,e.target.value)}>{stages.map(s=><option value={s} key={s}>{s}</option>)}</select></td><td>{l.nextFollowUpAt?new Date(l.nextFollowUpAt).toLocaleDateString():"—"}</td></tr>)}</tbody></table></div></div>}</div>}
