"use client";
import {useEffect,useRef,useState} from "react";
import {CreateModal,type CreateField} from "../components/create-modal";
import {Badge} from "../../components/ui/badge";
import {Button} from "../../components/ui/button";

const apiUrl=process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/,"")??"http://localhost:4000/api";
const stages=["NEW","CONTACTED","QUALIFIED","PROPOSAL","WON","LOST"] as const;
const hrOutcomes=["NOT_CALLED","NO_ANSWER","HR_INTERESTED","HR_NOT_NEEDED","OTHER_NEED_FOUND","NOT_INTERESTED"] as const;
const fields:CreateField[]=[{name:"firstName",label:"First name",required:true},{name:"lastName",label:"Last name",required:true},{name:"email",label:"Email",type:"email"},{name:"phone",label:"Phone",type:"tel"},{name:"title",label:"Job title"},{name:"company",label:"Company"},{name:"source",label:"Source"},{name:"status",label:"Status",type:"select",options:[...stages]},{name:"score",label:"Lead score (0-100)",type:"number"},{name:"estimatedValue",label:"Estimated value (ETB)",type:"number"},{name:"nextFollowUpAt",label:"Next follow-up",type:"date"},{name:"ownerId",label:"Owner",type:"select",options:[]}];

export default function Page(){
 const[data,setData]=useState<any[]>([]),[team,setTeam]=useState<any[]>([]),[error,setError]=useState(""),[view,setView]=useState<"kanban"|"table">("kanban");
 const[requestLead,setRequestLead]=useState<any>(null),[request,setRequest]=useState({problem:"",currentProcess:"",requestedSolution:"",message:""});
 const[search,setSearch]=useState(""),[statusFilter,setStatusFilter]=useState("ALL"),[hrFilter,setHrFilter]=useState("ALL"),[ownerFilter,setOwnerFilter]=useState("ALL"),[sourceFilter,setSourceFilter]=useState("");
 const[minScore,setMinScore]=useState(""),[maxScore,setMaxScore]=useState(""),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[pagination,setPagination]=useState({page:1,pageSize:25,total:0,totalPages:1});
 const[selected,setSelected]=useState<any>(null),[detailLoading,setDetailLoading]=useState(false),[loadingMore,setLoadingMore]=useState(false);
 const sentinel=useRef<HTMLDivElement|null>(null);

 const query=(requestedPage:number,size:number)=>{const q=new URLSearchParams({page:String(requestedPage),pageSize:String(size)});if(search.trim())q.set("search",search.trim());if(statusFilter!=="ALL")q.set("status",statusFilter);if(hrFilter!=="ALL")q.set("hrOutcome",hrFilter);if(ownerFilter!=="ALL")q.set("ownerId",ownerFilter);if(sourceFilter.trim())q.set("source",sourceFilter.trim());if(minScore!=="")q.set("minScore",minScore);if(maxScore!=="")q.set("maxScore",maxScore);return q};

 async function load(reset=true){
  try{
   const requestedPage=reset?page:1,size=pageSize;
   const[r,t]=await Promise.all([fetch(apiUrl+"/workspace/leads?"+query(requestedPage,size),{credentials:"include"}),fetch(apiUrl+"/workspace/team",{credentials:"include"})]);
   const b=await r.json();if(!r.ok)throw new Error(b.message||"Could not load leads");
   setData(Array.isArray(b.data)?b.data:[]);if(b.pagination)setPagination(b.pagination);
   if(t.ok){const tb=await t.json();setTeam(Array.isArray(tb.data)?tb.data:[])}setError("");
  }catch(e){setError(e instanceof Error?e.message:"Could not load leads")}
 }
 async function loadMore(){
  if(view!=="kanban"||loadingMore||pagination.page>=pagination.totalPages)return;
  setLoadingMore(true);
  try{const next=pagination.page+1,r=await fetch(apiUrl+"/workspace/leads?"+query(next,pageSize),{credentials:"include"}),b=await r.json();if(!r.ok)throw new Error(b.message||"Could not load more leads");setData(old=>[...old,...(b.data||[])]);setPagination(b.pagination)}
  catch(e){setError(e instanceof Error?e.message:"Could not load more leads")}finally{setLoadingMore(false)}
 }
 useEffect(()=>{setPage(1);const timer=setTimeout(()=>void load(),search?250:0);return()=>clearTimeout(timer)},[view,search,statusFilter,hrFilter,ownerFilter,sourceFilter,minScore,maxScore,pageSize]);
 useEffect(()=>{if(view==="table")void load()},[page]);
 useEffect(()=>{if(view!=="kanban"||!sentinel.current)return;const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting)void loadMore()},{rootMargin:"240px"});observer.observe(sentinel.current);return()=>observer.disconnect()},[view,pagination.page,pagination.totalPages,loadingMore,search,statusFilter,hrFilter,ownerFilter,sourceFilter,minScore,maxScore]);

 const ownerOptions=team.map((m:any)=>({value:m.user.id,label:[m.user.firstName,m.user.lastName].filter(Boolean).join(" ")}));
 const modalFields=fields.map(f=>f.name==="ownerId"?{...f,options:ownerOptions}:f) as any;
 async function create(values:Record<string,string>){const r=await fetch(apiUrl+"/workspace/leads",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});const b=await r.json();if(!r.ok)throw new Error(b.message||"Could not create lead");await load()}
 async function move(id:string,status:string){const previous=data;setData(x=>x.map(l=>l.id===id?{...l,status}:l));const r=await fetch(apiUrl+"/workspace/leads/"+id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok){setData(previous);setError("Could not update lead")}}
 async function setOutcome(lead:any,outcome:string){if(outcome==="OTHER_NEED_FOUND"){setRequestLead(lead);return}const r=await fetch(apiUrl+"/workspace/leads/"+lead.id+"/hr-outcome",{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({outcome})});if(!r.ok){setError("Could not update HR outcome");return}await load()}
 async function openDetail(lead:any){setSelected(lead);setDetailLoading(true);try{const r=await fetch(apiUrl+"/workspace/leads/"+lead.id+"/detail",{credentials:"include"}),b=await r.json();if(!r.ok)throw new Error(b.message||"Could not load lead detail");setSelected(b.data)}catch(e){setError(e instanceof Error?e.message:"Could not load lead detail")}finally{setDetailLoading(false)}}
 async function submitRequest(e:any){e.preventDefault();const r=await fetch(apiUrl+"/workspace/leads/"+requestLead.id+"/request",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(request)});const b=await r.json();if(!r.ok){setError(b.message||"Could not send request");return}setRequestLead(null);setRequest({problem:"",currentProcess:"",requestedSolution:"",message:""});await load()}
 const stop=(e:any)=>e.stopPropagation();
 const outcome=(l:any)=><select value={l.hrCallOutcome||"NOT_CALLED"} onClick={stop} onChange={e=>void setOutcome(l,e.target.value)}>{hrOutcomes.map(s=><option value={s} key={s}>{s.replaceAll("_"," ")}</option>)}</select>;

 return <div className="placeholderPage">
  <style>{`@keyframes leadReveal{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}.leadReveal{animation:leadReveal .28s ease both}`}</style>
  <header><div><p className="eyebrow">Sales workspace</p><h1>Leads</h1><p>Start with Hyaw Workforce. If HR is not the need, discover another business problem and send it to Admin.</p></div><div className="actions"><Button variant="outline" onClick={()=>setView(view==="kanban"?"table":"kanban")}>{view==="kanban"?"Table view":"Kanban view"}</Button><CreateModal entity="lead" fields={modalFields} onCreated={create}/></div></header>
  {error?<p className="dataError">{error}</p>:null}
  <div className="ui-card"><div className="ui-card-content" style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"end"}}>
   <label>Search<input className="ui-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, company, email, phone or source"/></label>
   <label>Status<select className="ui-input" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">All</option>{stages.map(s=><option key={s}>{s}</option>)}</select></label>
   <label>HR outcome<select className="ui-input" value={hrFilter} onChange={e=>setHrFilter(e.target.value)}><option value="ALL">All</option>{hrOutcomes.map(s=><option key={s}>{s.replaceAll("_"," ")}</option>)}</select></label>
   <label>Owner<select className="ui-input" value={ownerFilter} onChange={e=>setOwnerFilter(e.target.value)}><option value="ALL">All owners</option>{ownerOptions.map((o:any)=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>
   <label>Source<input className="ui-input" value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)} placeholder="e.g. AI Discovery"/></label>
   <label>Score from<input className="ui-input" type="number" min="0" max="100" value={minScore} onChange={e=>setMinScore(e.target.value)}/></label>
   <label>Score to<input className="ui-input" type="number" min="0" max="100" value={maxScore} onChange={e=>setMaxScore(e.target.value)}/></label>
   <label>Rows<select className="ui-input" value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}>{[10,25,50].map(n=><option key={n}>{n}</option>)}</select></label>
  </div></div>

  {view==="kanban"?<><div className="leadKanban">{stages.map(stage=><section className="kanbanColumn" key={stage} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData("leadId");if(id)void move(id,stage)}}><div className="kanbanHead"><strong>{stage}</strong><Badge>{data.filter(x=>x.status===stage).length}{pagination.page<pagination.totalPages?"+":""}</Badge></div><div className="kanbanCards">{data.filter(x=>x.status===stage).map((l,i)=><article className="leadCard leadReveal" style={{animationDelay:`${Math.min(i,12)*20}ms`,cursor:"pointer"}} draggable onDragStart={e=>e.dataTransfer.setData("leadId",l.id)} onClick={()=>void openDetail(l)} key={l.id}><div><strong>{l.firstName} {l.lastName}</strong><span>{l.company||"No company"}</span></div><p>{l.phone||l.email||"No contact"} · {l.source||"—"}</p><div className="leadMeta"><span>Score {l.score??0}</span><span>{l.owner?[l.owner.firstName,l.owner.lastName].join(" "):"Unassigned"}</span></div><select value={l.status} onClick={stop} onChange={e=>void move(l.id,e.target.value)}>{stages.map(s=><option key={s}>{s}</option>)}</select>{outcome(l)}</article>)}</div></section>)}</div><div ref={sentinel} style={{height:24,textAlign:"center",padding:8}}>{loadingMore?"Loading more leads…":pagination.page<pagination.totalPages?"Scroll for more":""}</div></>:
  <div className="ui-card"><div className="ui-card-content" style={{overflowX:"auto"}}><table className="ui-table"><thead><tr><th>Lead</th><th>Company</th><th>Contact</th><th>Source</th><th>Owner</th><th>Score</th><th>Status</th><th>HR outcome</th></tr></thead><tbody>{data.map(l=><tr key={l.id} onClick={()=>void openDetail(l)} style={{cursor:"pointer"}}><td><strong>{l.firstName} {l.lastName}</strong></td><td>{l.company||"—"}</td><td>{l.email||l.phone||"—"}</td><td>{l.source||"—"}</td><td>{l.owner?[l.owner.firstName,l.owner.lastName].join(" "):"Unassigned"}</td><td>{l.score??0}</td><td><select value={l.status} onClick={stop} onChange={e=>void move(l.id,e.target.value)}>{stages.map(s=><option key={s}>{s}</option>)}</select></td><td>{outcome(l)}</td></tr>)}</tbody></table>{!data.length?<p>No leads match these filters.</p>:null}</div></div>}

  {view==="table"?<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginTop:16}}><span>{pagination.total} leads · Page {pagination.page} of {pagination.totalPages}</span><div className="actions"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</Button><Button variant="outline" disabled={page>=pagination.totalPages} onClick={()=>setPage(p=>p+1)}>Next</Button></div></div>:null}

  {selected?<div style={{position:"fixed",inset:0,zIndex:85,background:"rgba(15,23,42,.35)",display:"flex",justifyContent:"flex-end"}} onMouseDown={()=>setSelected(null)}><aside className="ui-card" style={{width:"min(600px,100%)",height:"100%",borderRadius:0,overflowY:"auto"}} onMouseDown={stop}><div className="ui-card-content"><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><p className="eyebrow">{selected.status}</p><h2>{selected.company||[selected.firstName,selected.lastName].filter(Boolean).join(" ")}</h2></div><Button variant="ghost" onClick={()=>setSelected(null)}>×</Button></div>{detailLoading?<p>Loading details…</p>:<><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><p><strong>Contact</strong><br/>{selected.firstName} {selected.lastName}</p><p><strong>Phone</strong><br/>{selected.phone||"—"}</p><p><strong>Email</strong><br/>{selected.email||"—"}</p><p><strong>Title</strong><br/>{selected.title||"—"}</p><p><strong>Owner</strong><br/>{selected.owner?[selected.owner.firstName,selected.owner.lastName].filter(Boolean).join(" "):"Unassigned"}</p><p><strong>Score</strong><br/>{selected.score??0}</p><p><strong>Source</strong><br/>{selected.source||"—"}</p><p><strong>HR outcome</strong><br/>{(selected.hrCallOutcome||"NOT_CALLED").replaceAll("_"," ")}</p></div>{selected.discovery?<section><hr/><p className="eyebrow">AI discovery intelligence</p><h3>{selected.discovery.campaign?.name||"AI qualification"}</h3><p><strong>Fit:</strong> {selected.discovery.fitScore}% · <strong>Confidence:</strong> {selected.discovery.confidence||0}% · <strong>Priority:</strong> {selected.discovery.priority}</p><p><strong>Qualification:</strong> {selected.discovery.qualificationReason||"Needs review"}</p><p><strong>Location:</strong> {selected.discovery.location||"—"} · <strong>Industry:</strong> {selected.discovery.industry||selected.discovery.businessType||"—"}</p><h3>Likely problems</h3><p>{Array.isArray(selected.discovery.likelyProblems)?selected.discovery.likelyProblems.join(" · "):"—"}</p><h3>Calling strategy</h3><p>{selected.discovery.strategy||"—"}</p>{selected.discovery.openingLine?<blockquote>{selected.discovery.openingLine}</blockquote>:null}<p><strong>First call goal:</strong> {selected.discovery.firstCallGoal||"—"}</p>{selected.discovery.sourceUrl?<p><a href={selected.discovery.sourceUrl} target="_blank" rel="noreferrer">Open source evidence</a></p>:null}</section>:null}</>}</div></aside></div>:null}

  {requestLead?<div style={{position:"fixed",inset:0,zIndex:90,background:"rgba(15,23,42,.45)",display:"grid",placeItems:"center",padding:20}} onMouseDown={()=>setRequestLead(null)}><section className="ui-card" style={{width:"min(640px,100%)"}} onMouseDown={stop}><div className="ui-card-content"><p className="eyebrow">HR did not fit</p><h2>Send a new customer request</h2><p>Ask what problem <strong>{requestLead.company||requestLead.firstName}</strong> needs solved, then send the discovery to Admin.</p><form onSubmit={submitRequest} style={{display:"grid",gap:12}}><label>Customer problem<input className="ui-input" required value={request.problem} onChange={e=>setRequest(x=>({...x,problem:e.target.value}))}/></label><label>Current process<input className="ui-input" value={request.currentProcess} onChange={e=>setRequest(x=>({...x,currentProcess:e.target.value}))} placeholder="Excel, paper, WhatsApp, manual..."/></label><label>What they need<input className="ui-input" value={request.requestedSolution} onChange={e=>setRequest(x=>({...x,requestedSolution:e.target.value}))}/></label><label>Message to Admin<textarea className="ui-input" style={{minHeight:120}} required value={request.message} onChange={e=>setRequest(x=>({...x,message:e.target.value}))}/></label><div className="actions"><Button type="button" variant="outline" onClick={()=>setRequestLead(null)}>Cancel</Button><Button type="submit">Send new request</Button></div></form></div></section></div>:null}
 </div>
}
