"use client";
import { CreateModal, type CreateField } from "./create-modal";

const configs:Record<string,{entity:string;fields:CreateField[];button?:string}>={
 Leads:{entity:"lead",fields:[{name:"firstName",label:"First name",required:true},{name:"lastName",label:"Last name",required:true},{name:"email",label:"Email",type:"email"},{name:"phone",label:"Phone",type:"tel"},{name:"company",label:"Company"},{name:"source",label:"Source",type:"select",options:["Website","Referral","Cold call","Social media","Event","Other"]},{name:"estimatedValue",label:"Estimated value",type:"number"},{name:"notes",label:"Notes",type:"textarea"}]},
 Contacts:{entity:"contact",fields:[{name:"name",label:"Full name",required:true},{name:"email",label:"Email",type:"email"},{name:"phone",label:"Phone",type:"tel"},{name:"company",label:"Company"},{name:"jobTitle",label:"Job title"},{name:"notes",label:"Notes",type:"textarea"}]},
 Companies:{entity:"company",fields:[{name:"name",label:"Company name",required:true},{name:"industry",label:"Industry"},{name:"phone",label:"Phone",type:"tel"},{name:"email",label:"Email",type:"email"},{name:"website",label:"Website"},{name:"address",label:"Address",type:"textarea"}]},
 Opportunities:{entity:"opportunity",fields:[{name:"name",label:"Opportunity name",required:true},{name:"company",label:"Company",required:true},{name:"value",label:"Value",type:"number"},{name:"stage",label:"Stage",type:"select",options:["New","Contacted","Qualified","Proposal","Won","Lost"]},{name:"closeDate",label:"Expected close",type:"date"},{name:"notes",label:"Notes",type:"textarea"}]},
 Pipeline:{entity:"pipeline",fields:[{name:"name",label:"Pipeline name",required:true},{name:"description",label:"Description",type:"textarea"}]},
 Activities:{entity:"activity",fields:[{name:"subject",label:"Subject",required:true},{name:"type",label:"Type",type:"select",options:["Call","Email","Meeting","Note","Status change"]},{name:"date",label:"Date",type:"date"},{name:"relatedTo",label:"Related lead/contact"},{name:"notes",label:"Notes",type:"textarea"}]},
 Tasks:{entity:"task",fields:[{name:"title",label:"Task",required:true},{name:"dueDate",label:"Due date",type:"date"},{name:"priority",label:"Priority",type:"select",options:["Low","Medium","High","Urgent"]},{name:"assignee",label:"Assignee"},{name:"description",label:"Description",type:"textarea"}]},
 Reports:{entity:"report",fields:[{name:"name",label:"Report name",required:true},{name:"type",label:"Report type",type:"select",options:["Sales","Pipeline","Lead conversion","Activity","Team performance"]},{name:"description",label:"Description",type:"textarea"}]},
 Team:{entity:"team member",button:"Invite member",fields:[{name:"name",label:"Full name",required:true},{name:"email",label:"Email",type:"email",required:true},{name:"role",label:"Role label"},{name:"message",label:"Invitation message",type:"textarea"}]},
 "Roles & permissions":{entity:"role",fields:[{name:"name",label:"Role name",required:true},{name:"description",label:"Description",type:"textarea"}]},
 Settings:{entity:"workspace setting",button:"Add setting",fields:[{name:"name",label:"Setting name",required:true},{name:"value",label:"Value",required:true},{name:"description",label:"Description",type:"textarea"}]}
};
export function PlaceholderPage({title,description}:{title:string;description:string}){const c=configs[title];return <div className="placeholderPage"><header><div><p className="eyebrow">Sales workspace</p><h1>{title}</h1><p>{description}</p></div>{c&&<CreateModal entity={c.entity} fields={c.fields} buttonLabel={c.button}/>}</header><section className="panel emptyState"><strong>{title} workspace</strong><p>Create your first item or continue managing existing records here.</p>{c&&<CreateModal entity={c.entity} fields={c.fields} buttonLabel={c.button}/>}</section></div>}
