"use client";
import {useEffect,useState} from "react";
import {CreateModal,type CreateField} from "./create-modal";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "../../components/ui/card";
import {Badge} from "../../components/ui/badge";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "../../components/ui/table";
const apiUrl=process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/,"")??"http://localhost:4000/api";
const cfg:any={
 Leads:{resource:"leads",entity:"lead",fields:[{name:"firstName",label:"First name",required:true},{name:"lastName",label:"Last name",required:true},{name:"email",label:"Email",type:"email"},{name:"phone",label:"Phone",type:"tel"},{name:"company",label:"Company"},{name:"source",label:"Source",type:"select",options:["Website","Referral","Cold call","Social media","Event","Other"]},{name:"estimatedValue",label:"Estimated value",type:"number"}],cols:[["Name",(x:any)=>x.firstName+" "+x.lastName],["Company",(x:any)=>x.company||"—"],["Status",(x:any)=><Badge>{x.status}</Badge>],["Value",(x:any)=>"ETB "+Number(x.estimatedValue||0).toLocaleString()],["Owner",(x:any)=>x.owner?x.owner.firstName+" "+x.owner.lastName:"Unassigned"]]},
 Contacts:{resource:"contacts",entity:"contact",fields:[{name:"name",label:"Full name",required:true},{name:"email",label:"Email",type:"email"},{name:"phone",label:"Phone",type:"tel"},{name:"company",label:"Company"},{name:"jobTitle",label:"Job title"},{name:"notes",label:"Notes",type:"textarea"}],cols:[["Name",(x:any)=>x.name],["Company",(x:any)=>x.company||"—"],["Job title",(x:any)=>x.jobTitle||"—"],["Email",(x:any)=>x.email||"—"],["Phone",(x:any)=>x.phone||"—"]]},
 Companies:{resource:"companies",entity:"company",fields:[{name:"name",label:"Company name",required:true},{name:"industry",label:"Industry"},{name:"phone",label:"Phone",type:"tel"},{name:"email",label:"Email",type:"email"},{name:"website",label:"Website"},{name:"address",label:"Address",type:"textarea"}],cols:[["Company",(x:any)=>x.name],["Industry",(x:any)=>x.industry||"—"],["Email",(x:any)=>x.email||"—"],["Phone",(x:any)=>x.phone||"—"],["Website",(x:any)=>x.website||"—"]]},
 Opportunities:{resource:"opportunities",entity:"opportunity",fields:[{name:"name",label:"Opportunity name",required:true},{name:"company",label:"Company"},{name:"value",label:"Value",type:"number"},{name:"stage",label:"Stage",type:"select",options:["NEW","CONTACTED","QUALIFIED","PROPOSAL","WON","LOST"]},{name:"closeDate",label:"Expected close",type:"date"},{name:"notes",label:"Notes",type:"textarea"}],cols:[["Opportunity",(x:any)=>x.name],["Company",(x:any)=>x.company||"—"],["Stage",(x:any)=><Badge>{x.stage}</Badge>],["Value",(x:any)=>"ETB "+Number(x.value||0).toLocaleString()],["Close date",(x:any)=>x.closeDate?new Date(x.closeDate).toLocaleDateString():"—"]]},
 Activities:{resource:"activities",entity:"activity",fields:[{name:"subject",label:"Subject",required:true},{name:"type",label:"Type",type:"select",options:["CALL","EMAIL","MEETING","NOTE","STATUS_CHANGE"]},{name:"body",label:"Notes",type:"textarea"}],cols:[["Activity",(x:any)=>x.subject],["Type",(x:any)=><Badge>{x.type}</Badge>],["Lead",(x:any)=>x.lead?x.lead.firstName+" "+x.lead.lastName:"—"],["By",(x:any)=>x.user?x.user.firstName+" "+x.user.lastName:"—"],["Created",(x:any)=>new Date(x.createdAt).toLocaleString()]]},
 Tasks:{resource:"tasks",entity:"task",fields:[{name:"title",label:"Task",required:true},{name:"dueDate",label:"Due date",type:"date"},{name:"priority",label:"Priority",type:"select",options:["LOW","MEDIUM","HIGH","URGENT"]},{name:"assignee",label:"Assignee"},{name:"description",label:"Description",type:"textarea"}],cols:[["Task",(x:any)=>x.title],["Priority",(x:any)=><Badge>{x.priority}</Badge>],["Assignee",(x:any)=>x.assignee||"—"],["Due",(x:any)=>x.dueDate?new Date(x.dueDate).toLocaleDateString():"—"],["Status",(x:any)=>x.completed?"Completed":"Open"]]}
};
export function WorkspaceDataPage({title,description}:{title:string;description:string}){const c=cfg[title];const[data,setData]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 async function load(){setLoading(true);try{const r=await fetch(apiUrl+"/workspace/"+c.resource,{credentials:"include"});const b=await r.json();if(!r.ok)throw new Error(b.message||"Could not load data");setData(Array.isArray(b.data)?b.data:[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load data")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function create(values:Record<string,string>){const r=await fetch(apiUrl+"/workspace/"+c.resource,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});const b=await r.json();if(!r.ok)throw new Error(b.message||"Could not create record");await load()}
 return <div className="placeholderPage"><header><div><p className="eyebrow">Sales workspace</p><h1>{title}</h1><p>{description}</p></div><CreateModal entity={c.entity} fields={c.fields as CreateField[]} onCreated={create}/></header><Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>Live records from your workspace database.</CardDescription></CardHeader><CardContent>{error?<p className="dataError">{error}</p>:loading?<p>Loading...</p>:<Table><TableHeader><TableRow>{c.cols.map((x:any)=><TableHead key={x[0]}>{x[0]}</TableHead>)}</TableRow></TableHeader><TableBody>{data.length?data.map((row:any)=><TableRow key={row.id}>{c.cols.map((x:any)=><TableCell key={x[0]}>{x[1](row)}</TableCell>)}</TableRow>):<TableRow><TableCell colSpan={c.cols.length}>No records yet.</TableCell></TableRow>}</TableBody></Table>}</CardContent></Card></div>}
