"use client";
import {useEffect,useState} from "react";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "../../components/ui/card";
import {Badge} from "../../components/ui/badge";
import {Button} from "../../components/ui/button";
const apiUrl=process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/,"")??"http://localhost:4000/api";
export function WorkspaceModulePage({kind,title,description}:{kind:string;title:string;description:string}){const[data,setData]=useState<any>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 async function load(){try{const r=await fetch(apiUrl+"/workspace/"+kind,{credentials:"include"});const b=await r.json();if(!r.ok)throw new Error(b.message||"Could not load");setData(b.data)}catch(e){setError(e instanceof Error?e.message:"Could not load")}}
 useEffect(()=>{void load()},[kind]);
 async function saveSettings(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const values=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch(apiUrl+"/workspace/settings",{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});setSaving(false);if(r.ok)await load();else setError("Could not save settings")}
 let body:any=<p>Loading...</p>;
 if(error)body=<p className="dataError">{error}</p>;
 else if(data&&kind==="pipeline")body=<div className="moduleGrid">{(data.pipelines||[]).map((p:any)=><Card key={p.id}><CardHeader><CardTitle>{p.name}</CardTitle><CardDescription>{p.isDefault?"Default pipeline":"Pipeline"}</CardDescription></CardHeader><CardContent><div className="recordList">{p.stages.map((s:any)=><div key={s.id}><strong>{s.position}. {s.name}</strong><Badge>{s.probability}%</Badge></div>)}</div></CardContent></Card>)}<Card><CardHeader><CardTitle>Live opportunities</CardTitle></CardHeader><CardContent><div className="recordList">{(data.opportunities||[]).map((o:any)=><div key={o.id}><span><strong>{o.name}</strong><small>{o.company||"No company"}</small></span><span><Badge>{o.stage}</Badge> ETB {Number(o.value).toLocaleString()}</span></div>)}</div></CardContent></Card></div>;
 else if(data&&kind==="team")body=<Card><CardContent><div className="recordList">{data.map((m:any)=><div key={m.id}><span><strong>{m.user.firstName} {m.user.lastName}</strong><small>{m.user.email}</small></span><span><Badge>{m.role?.name||"NO ROLE"}</Badge> {m.user.active?"Active":"Disabled"}</span></div>)}</div></CardContent></Card>;
 else if(data&&kind==="roles")body=<div className="moduleGrid">{data.map((r:any)=><Card key={r.id}><CardHeader><CardTitle>{r.name}</CardTitle><CardDescription>{r.description||"Workspace role"} · {r._count?.members||0} members</CardDescription></CardHeader><CardContent><div className="permissionTags">{r.permissions.map((p:any)=><Badge key={p.permission.id}>{p.permission.key}</Badge>)}</div></CardContent></Card>)}</div>;
 else if(data&&kind==="reports")body=<><div className="stats">{[["Leads",data.leads],["Won",data.won],["Lost",data.lost],["Activities",data.activities],["Pipeline","ETB "+Number(data.pipeline).toLocaleString()]].map(x=><Card key={x[0]}><CardContent><span>{x[0]}</span><strong>{x[1]}</strong></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Lead stages</CardTitle><CardDescription>Live conversion distribution</CardDescription></CardHeader><CardContent><div className="recordList">{data.byStage.map((x:any)=><div key={x.stage}><strong>{x.stage}</strong><Badge>{x.count}</Badge></div>)}</div></CardContent></Card></>;
 else if(data&&kind==="settings")body=<Card><CardHeader><CardTitle>Workspace settings</CardTitle><CardDescription>Saved to PostgreSQL for this business.</CardDescription></CardHeader><CardContent><form className="workspaceSettings" onSubmit={saveSettings}><label>Workspace name<input name="workspaceName" defaultValue={data.workspaceName||"Hyaw CRM"}/></label><label>Timezone<input name="timezone" defaultValue={data.timezone||"Africa/Addis_Ababa"}/></label><label>Currency<input name="currency" defaultValue={data.currency||"ETB"}/></label><label>Lead assignment<select name="leadAssignment" defaultValue={data.leadAssignment||"manual"}><option value="manual">Manual</option><option value="round_robin">Round robin</option></select></label><Button disabled={saving}>{saving?"Saving...":"Save settings"}</Button></form></CardContent></Card>;
 return <div><header><div><p className="eyebrow">Sales workspace</p><h1>{title}</h1><p>{description}</p></div></header>{body}</div>}
